# Generated by Django 5.2.5 on 2025-08-31 19:27

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_photo_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='path_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_directory_path),
        ),
    ]
